on: [push]

jobs:
  swagger:
    runs-on: ubuntu-latest
    name: A job to generate swagger ui.
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swagger ui action
      id: swagger-ui-action
      uses: ./
      with:
        dir: './'
        pattern: '*.json'
        debug: 'true'
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: swagger-ui