on: [push]

jobs:
  swagger:
    runs-on: ubuntu-latest
    name: A job to generate swagger ui.
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swagger ui action
      id: swagger-ui-action
      uses: ./
      with:
        dir: './'
        pattern: '*.json'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
